### ISSUE TITLE
READONLY You can't write against a read only slave.

### ISSUE THREAD

**Issue by sguilly** [thomasjpfan/redis-cluster-docker-swarm#6]
I am success to start the stack on a swarm cluster.

i am success to connect with redis-cli and externaly with "redis desktop manager".

But when i try to execute a simple command "set foo bar", i receive this error : "-READONLY You can't write against a read only slave."

Thanks for your help...

**Comment by thomasjpfan** [comment]
You need to use to the Redis Sentinel to get current the master, then use that information to log into the master.

You can read about Redis Sentinel here: https://redis.io/topics/sentinel
